<?php

namespace Database\Seeders;

use App\Models\ExternalOrderExcelValue;
use Illuminate\Database\Seeder;

class ExternalOrderExcelValueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $flowmeter_order_id = 1;
        $flowmeter_worksheet = [
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I2', 'value' => '1 / III - 22 / E - 0.0 DL'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E5', 'value' => 'Avico'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E6', 'value' => '-'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E7', 'value' => '-'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E8', 'value' => '1'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E9', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E10', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E11', 'value' => 'Laboratorium Kalibrasi LPFK Banjarbaru'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E12', 'value' => 'IGD'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E17', 'value' => 22.4],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F17', 'value' => 22.7],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E18', 'value' => 67.4],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F18', 'value' => 67.8],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E22', 'value' => 'Baik'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B38', 'value' => 'Pembacaan skala dibawah bola'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B41', 'value' => 'Gas Flow Analyzer, Merek : Fluke, Model : VT900A, SN : 5101752-5102038'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B42', 'value' => 'Thermohygrolight, Merek : KIMO, Model : KH-210-AO, SN : 15062873'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B49', 'value' => 'Muhammad Irfan Husnuzhzhan']
        ];

        $timbangan_bayi_order_id = 2;
        $timbangan_bayi_worksheet = [
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'I2', 'value' => '3 / I - 17 / E - 001.03 DL'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D4', 'value' => '-'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D5', 'value' => '-'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D6', 'value' => '-'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D7', 'value' => 0.005],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F7', 'value' => 'Digital'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D8', 'value' => '2022-01-15'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D9', 'value' => '2022-01-15'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D10', 'value' => 'laboratorium kalibrasi lpfk banjarbaru'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D11', 'value' => 'laboratorium kalibrasi lpfk banjarbaru'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D16', 'value' => 22],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E16', 'value' => 24],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D17', 'value' => 60],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E17', 'value' => 63],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D22', 'value' => 'Baik'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C30', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D30', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F30', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G30', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C31', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D31', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F31', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G31', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C32', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D32', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F32', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G32', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C33', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D33', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F33', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G33', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C34', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D34', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F34', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G34', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C35', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D35', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F35', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G35', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C36', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D36', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F36', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G36', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C37', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D37', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F37', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G37', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C38', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D38', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F38', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G38', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C39', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D39', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F39', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G39', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C44', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D44', 'value' => 1.05],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E44', 'value' => 1.05],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F44', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C45', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D45', 'value' => 2],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E45', 'value' => 2],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F45', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C46', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D46', 'value' => 3],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E46', 'value' => 3],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F46', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C48', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D48', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E48', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F48', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C53', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D53', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E53', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F53', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'B68', 'value' => 'Anak Timbangan Standar, Merek : HÄFNER, Model : 7.MEHM-210, SN : 1060716'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'B72', 'value' => 'Thermohygrolight, Merek : KIMO, Model : KH-210-AO, SN : 15062874'],
        ];

        $nebulizer_order_id = 3;
        $nebulizer_worksheet = [
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I2', 'value' => '1 / III - 22 / E - 0.0 DL'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E4', 'value' => 'OMRON'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E5', 'value' => 'CX 4'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E6', 'value' => '1946'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E7', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E8', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E9', 'value' => 'Laboratorium Kalibrasi LPFK Banjarbaru'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E10', 'value' => 'P2M'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E15', 'value' => 25.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'F15', 'value' => 25.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E16', 'value' => 70.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'F16', 'value' => 70.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E17', 'value' => 228],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E20', 'value' => 'Baik'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I25', 'value' => 7],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'C26', 'value' => 'Resistansi Pembumian Protektif (kabel tidak dapat dilepas)'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I26', 'value' => 0.120],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'C27', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I27', 'value' => 12.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'C32', 'value' => 'Flow (L/min) (Compressor)'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E32', 'value' => 4.3],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'F32', 'value' => 4.2],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'G32', 'value' => 4.3],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B42', 'value' => 'Gas Flow Analyzer, Merek : Fluke, Model : VT305, SN : BF102163'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B43', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 2853077'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B44', 'value' => 'Thermohygrolight, Merek : Greisinger, Model : GFTB 200, SN : 34904091'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B51', 'value' => 'Ryan Rama Chaesar R'],
        ];

        $suction_pump_order_id = 4;
        $suction_pump_worksheet = [
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'I2', 'value' => '6 / II - 21 / E - 012.12 DL'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C4', 'value' => 'SMAF'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C5', 'value' => 'YX980D'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C6', 'value' => 'D11-18-047'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C7', 'value' => '-50'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C8', 'value' => '2022-01-03'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C9', 'value' => '2022-01-03'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C10', 'value' => 'Ruang Bersalin'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C11', 'value' => 'Ruang Bersalin'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C12', 'value' => '(Surgical, Tracheal, Uterine)'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E8', 'value' => 'Digital Pressure Meter, Merek : Fluke Biomedical, Model : DPM 4-2G, SN : 1831021'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E9', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 620, SN : 1837056'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E10', 'value' => 'Digital Thermohygrobarometer, Merek : EXTECH, Model : SD700, SN : A.100617'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C30', 'value' => 'Baik'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C31', 'value' => 'Baik'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B24', 'value' => 24.6],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C24', 'value' => 24.8],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B25', 'value' => 82.3],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C25', 'value' => 82.5],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B26', 'value' => 200],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B27', 'value' => 1007.5],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G35', 'value' => '-'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A36', 'value' => 'Resistansi pembumian protektif (kabel dapat dilepas) (Ω)'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G36', 'value' => '-'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A37', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas II (µA)'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G37', 'value' => '-'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'D59', 'value' => 'mmHg ke mmHg'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'F59', 'value' => 'mmHg ke mmHg'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'H59', 'value' => 'mmHg ke mmHg'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'K78', 'value' => 'mBar ke mmHg'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A61', 'value' => 200],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A62', 'value' => 300],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A63', 'value' => 400],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A64', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A65', 'value' => 600],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B61', 'value' => 190],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B62', 'value' => 280],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B63', 'value' => 370],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B64', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B65', 'value' => 1],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C61', 'value' => 190],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C62', 'value' => 280],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C63', 'value' => 370],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C64', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'C65', 'value' => 1],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'D61', 'value' => 190],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'D62', 'value' => 280],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'D63', 'value' => 370],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'D64', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'D65', 'value' => 1],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E61', 'value' => 190],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E62', 'value' => 280],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E63', 'value' => 370],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E64', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'E65', 'value' => 1],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'F61', 'value' => 190],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'F62', 'value' => 280],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'F63', 'value' => 370],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'F64', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'F65', 'value' => 1],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G61', 'value' => 190],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G62', 'value' => 280],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G63', 'value' => 370],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G64', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'G65', 'value' => 1],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B79', 'value' => 500],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'B80', 'value' => 'Muhammad Alpian Hadi'],
            ['external_alkes_order_id' => $suction_pump_order_id, 'cell' => 'A87', 'value' => 'Catu daya menggunakan baterai'],
        ];

        $patient_monitor_order_id = 5;
        $patient_monitor_worksheet = [
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I2', 'value' => '1 / I - 22 / / E - 010.26 DL'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F4', 'value' => 'Medi Globe'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F5', 'value' => 'Garuda 12'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F6', 'value' => 'G122008063'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F7', 'value' => '2022-01-19'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F8', 'value' => '2022-01-19'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F9', 'value' => 'OK'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F10', 'value' => 'OK'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F14', 'value' => 26.6],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G14', 'value' => 26.5],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F15', 'value' => 68.3],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G15', 'value' => 68.7],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F16', 'value' => 204.8],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F19', 'value' => 'Baik'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F20', 'value' => 'Baik'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J25', 'value' => 'OL'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'C26', 'value' => 'Resistansi Pembumian Protektif (kabel dapat dilepas)'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J26', 'value' => 0.223],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'C27', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J27', 'value' => 600],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J28', 'value' => 10],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'C35', 'value' => 'Heart Rate (BPM)'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E35', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E36', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E37', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E38', 'value' => 180],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F35', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F36', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F37', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F38', 'value' => 180],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G35', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G36', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G37', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G38', 'value' => 180],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H35', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H36', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H37', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H38', 'value' => 180],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I35', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I36', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I37', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I38', 'value' => 180],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J35', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J36', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J37', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J38', 'value' => 180],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E44', 'value' => 90],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E45', 'value' => 95],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E46', 'value' => 98],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E47', 'value' => 99],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E48', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F44', 'value' => 90],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F45', 'value' => 95],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F46', 'value' => 98],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F47', 'value' => 99],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F48', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G44', 'value' => 90],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G45', 'value' => 95],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G46', 'value' => 98],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G47', 'value' => 99],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G48', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H44', 'value' => 90],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H45', 'value' => 95],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H46', 'value' => 98],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H47', 'value' => 99],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H48', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I44', 'value' => 90],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I45', 'value' => 95],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I46', 'value' => 98],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I47', 'value' => 99],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I48', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J44', 'value' => 90],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J45', 'value' => 95],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J46', 'value' => 98],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J47', 'value' => 99],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J48', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'D62', 'value' => 'Dewasa'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E54', 'value' => 1],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E55', 'value' => 1],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E56', 'value' => 1],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E57', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E58', 'value' => 200],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E59', 'value' => 150],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E60', 'value' => 82],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E61', 'value' => 53],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F54', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F55', 'value' => 80],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F56', 'value' => 150],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F57', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F58', 'value' => 200],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F59', 'value' => 150],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F60', 'value' => 82],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F61', 'value' => 53],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G54', 'value' => 120],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G55', 'value' => 80],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G56', 'value' => 150],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G57', 'value' => 100],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G58', 'value' => 200],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G59', 'value' => 150],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G60', 'value' => 82],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G61', 'value' => 52],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E70', 'value' => 1],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E71', 'value' => 1],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E72', 'value' => 40],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'E73', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F70', 'value' => 20],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F71', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F72', 'value' => 40],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'F73', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G70', 'value' => 20],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G71', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G72', 'value' => 40],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'G73', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H70', 'value' => 20],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H71', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H72', 'value' => 40],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'H73', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I70', 'value' => 20],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I71', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I72', 'value' => 40],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'I73', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J70', 'value' => 20],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J71', 'value' => 30],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J72', 'value' => 40],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'J73', 'value' => 60],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'B89', 'value' => 'Vital Sign Simulator, Merek : Fluke Biomedical, Model : Prosim 8, SN : 3217028'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'B91', 'value' => 'Vital Sign Simulator, Merek : Fluke Biomedical, Model : Prosim 8, SN : 3217028'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'B93', 'value' => 'Vital Sign Simulator, Merek : Fluke Biomedical, Model : Prosim 8, SN : 3217028'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'B95', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 4670010'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'B97', 'value' => 'Thermohygrolight, Merek : KIMO, Model : KH-210-AO, SN : 15062872'],
            ['external_alkes_order_id' => $patient_monitor_order_id, 'cell' => 'B103', 'value' => 'Muhammad Iqbal Saiful Rahman'],
        ];

        $centrifuge_order_id = 6;
        $centrifuge_worksheet = [
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I2', 'value' => '1 / 1 - 21 / E - 000.00 DL'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E6', 'value' => 'Hettich'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E7', 'value' => 'EBA 21'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E8', 'value' => '2019021001'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E9', 'value' => 1],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'G9', 'value' => '( Analog )'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E10', 'value' => '2021-10-14'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E11', 'value' => '2021-10-14'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E12', 'value' => 'Laboratorium'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E13', 'value' => 'Laboratorium'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E18', 'value' => 26.7],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E19', 'value' => 27.7],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'F18', 'value' => 73.3],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'F19', 'value' => 72],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E20', 'value' => 220],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E23', 'value' => 'Baik'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'E24', 'value' => 'Baik'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I28', 'value' => "OL"],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'C29', 'value' => 'Resistansi Pembumian Protektif (kabel dapat dilepas)'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I29', 'value' => 0.1],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'C30', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I30', 'value' => 10],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'D36', 'value' => 2000],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'D37', 'value' => 4000],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'D38', 'value' => 6000],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'D39', 'value' => 8000],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'F36', 'value' => 2000.2],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'F37', 'value' => 4000.2],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'F38', 'value' => 6000.2],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'F39', 'value' => 8000.2],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'G36', 'value' => 1998.8],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'G37', 'value' => 4000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'G38', 'value' => 6000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'G39', 'value' => 8000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'H36', 'value' => 1998.8],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'H37', 'value' => 4000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'H38', 'value' => 6000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'H39', 'value' => 8000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I36', 'value' => 1998.8],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I37', 'value' => 4000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I38', 'value' => 6000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'I39', 'value' => 8000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'J36', 'value' => 1998.8],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'J37', 'value' => 4000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'J38', 'value' => 6000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'J39', 'value' => 8000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'K36', 'value' => 1998.8],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'K37', 'value' => 4000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'K38', 'value' => 6000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'K39', 'value' => 8000.4],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'D44', 'value' => 300],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'F44', 'value' => 444],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'H44', 'value' => 444],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'J44', 'value' => 444],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'B55', 'value' => 'Digital Tachometer, Merek : Krisbow, Model : KW06-563, SN : 180812206'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'B56', 'value' => 'Stopwatch, Merek : EXTECH, Model : 365535, SN : 005018'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'B57', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 4669058'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'B58', 'value' => 'Thermohygrobarometer, Merek : EXTECH, Model : SD700, SN : A.100618'],
            ['external_alkes_order_id' => $centrifuge_order_id, 'cell' => 'B65', 'value' => 'Gusti Arya Dinata'],
        ];

        $dental_unit_order_id = 7;
        $dental_unit_worksheet = [
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'I2', 'value' => '19 / III - 25 / E - 009.678 DL'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E4', 'value' => 'GNATUS'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E5', 'value' => 'SYNCRUS LS'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E6', 'value' => '081298408556'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E7', 'value' => '31 Januari 2020'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E8', 'value' => '31 Januari 2020'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E9', 'value' => 'LPFK BJB'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E10', 'value' => 'LPFK BJB'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E15', 'value' => 23.5],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F15', 'value' => 23.4],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E16', 'value' => 57.4],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F16', 'value' => 57.6],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E17', 'value' => 225],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E20', 'value' => 'Baik'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H25', 'value' => 'OL'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'C26', 'value' => 'Resistansi Pembumian Protektif (kabel tidak dapat dilepas)'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H26', 'value' => 0.100],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'C27', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H27', 'value' => 600],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E32', 'value' => 8],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E33', 'value' => 99000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E34', 'value' => 22000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E35', 'value' => 7],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E36', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'E37', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F32', 'value' => 8],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F33', 'value' => 99000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F34', 'value' => 22000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F35', 'value' => 7],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F36', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'F37', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'G32', 'value' => 8],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'G33', 'value' => 99000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'G34', 'value' => 22000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'G35', 'value' => 7],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'G36', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'G37', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H32', 'value' => 8],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H33', 'value' => 99000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H34', 'value' => 22000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H35', 'value' => 7],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H36', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'H37', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'I32', 'value' => 8],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'I33', 'value' => 99000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'I34', 'value' => 22000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'I35', 'value' => 7],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'I36', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'I37', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'J32', 'value' => 8],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'J33', 'value' => 99000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'J34', 'value' => 22000],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'J35', 'value' => 7],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'J36', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'J37', 'value' => -150],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'B51', 'value' => 'Digital Tachometer, Merek : Compact Instrument, Model : CT6/LSR/ERP, SN : 631341'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'B52', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 4670010'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'B53', 'value' => 'Digital Lux Meter, Merek : EXTECH, Model : Easy View 30, SN : 110705875'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'B54', 'value' => 'Digital Pressure Meter, Merek : Fluke, Model : DPM 4-2G, SN : 4821027'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'B55', 'value' => 'Thermohygrolight, Merek : Greisinger, Model : GFTB 200, SN : 34903051'],
            ['external_alkes_order_id' => $dental_unit_order_id, 'cell' => 'B62', 'value' => 'Gusti Arya Dinata'],
        ];

        $fetal_doppler_order_id = 8;
        $fetal_doppler_worksheet = [
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I2', 'value' => "1 / IV - 21 / E - 00.000 DL"],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E4', 'value' => "Bistos"],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E5', 'value' => "BT - 200"],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E6', 'value' => 'BDH10736'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E7', 'value' => 1],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E8', 'value' => '2022-04-03'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E9', 'value' => '2022-04-03'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E10', 'value' => 'IGD'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E11', 'value' => 'IGD'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E16', 'value' => 24],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F16', 'value' => 25],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E17', 'value' => 79],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F17', 'value' => 80],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E18', 'value' => 220],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E22', 'value' => 'Baik'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I27', 'value' => 'OL'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I28', 'value' => 0.01],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'C29', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I29', 'value' => 50],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E34', 'value' => 30],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E35', 'value' => 60],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E36', 'value' => 90],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E37', 'value' => 120],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E38', 'value' => 150],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E39', 'value' => 180],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'E40', 'value' => 180],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F34', 'value' => 30],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F35', 'value' => 60],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F36', 'value' => 90],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F37', 'value' => 120],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F38', 'value' => 150],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F39', 'value' => 180],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'F40', 'value' => 210],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'G34', 'value' => 30],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'G35', 'value' => 60],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'G36', 'value' => 90],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'G37', 'value' => 120],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'G38', 'value' => 150],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'G39', 'value' => 180],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'G40', 'value' => 210],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'H34', 'value' => 30],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'H35', 'value' => 60],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'H36', 'value' => 90],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'H37', 'value' => 120],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'H38', 'value' => 150],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'H39', 'value' => 180],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'H40', 'value' => 210],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I34', 'value' => 30],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I35', 'value' => 60],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I36', 'value' => 90],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I37', 'value' => 120],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I38', 'value' => 150],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I39', 'value' => 180],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'I40', 'value' => 210],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'B43', 'value' => 'Ketidakpastian pengukuran dilaporkan pada tingkat kepercayaan 95% dengan faktor cakupan k= 2'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'B50', 'value' => 'Fetal Simulator, Merek : Fluke Biomedical, Model : PS 320, SN : 4662032'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'B51', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 3699030'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'B52', 'value' => 'Digital Thermohygrobarometer, Merek : EXTECH, Model : SD700, SN : A.100586'],
            ['external_alkes_order_id' => $fetal_doppler_order_id, 'cell' => 'B59', 'value' => 'Septia Khairunnisa'],
        ];

        $ecg_recorder_order_id = 9;
        $ecg_recorder_worksheet = [
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I2', 'value' => '10 / III - 21 / E - 003.30 DL'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E4', 'value' => 'MED Cardio'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E5', 'value' => 'ECG - 3303B'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E6', 'value' => 'ECG - 3303B1701075'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E7', 'value' => '2021-03-25'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E8', 'value' => '2021-03-25'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E9', 'value' => 'Poli Geriatri'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E10', 'value' => 'Poli Geriatri'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E14', 'value' => 25],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'F14', 'value' => 25.3],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E15', 'value' => 65.1],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'F15', 'value' => 65.2],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E16', 'value' => 224],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E19', 'value' => 'Baik'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'E20', 'value' => 'Baik'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I25', 'value' => 'OL'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'C26', 'value' => 'Resistansi Pembumian Protektif (kabel tidak dapat dilepas)'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I26', 'value' => 'OL'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'C27', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I27', 'value' => 700],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I28', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'F34', 'value' => 'Baik'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'G40', 'value' => 4.93],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'G41', 'value' => 9.92],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'G42', 'value' => 20.28],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'H40', 'value' => 4.93],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'H41', 'value' => 9.92],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'H42', 'value' => 20.28],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I40', 'value' => 4.93],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I41', 'value' => 9.92],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I42', 'value' => 20.28],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'J40', 'value' => 4.93],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'J41', 'value' => 9.92],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'J42', 'value' => 20.28],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'K40', 'value' => 4.93],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'K41', 'value' => 9.92],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'K42', 'value' => 20.28],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'F47', 'value' => 104],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'G47', 'value' => 104],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'H47', 'value' => 104],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'F51', 'value' => 100.12],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'G51', 'value' => 100.11],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'H51', 'value' => 100.12],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'H56', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I56', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'J56', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'K56', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'L56', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'H61', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'I61', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'J61', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'K61', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'L61', 'value' => 20],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'B72', 'value' => 'Multiparameter Simulator, Merek : RIGEL, Model : PatSim200, SN : 15L-0684'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'B73', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 4669058'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'B74', 'value' => 'Digital Caliper, Merek : Mitutoyo, Model : CD-6"PSX, SN : 11011858'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'B75', 'value' => 'Thermohygrobarometer, Merek : EXTECH, Model : SD700, SN : A.100616'],
            ['external_alkes_order_id' => $ecg_recorder_order_id, 'cell' => 'B82', 'value' => 'Muhammad Iqbal Saiful Rahman'],
        ];

        $infusion_pump_order_id = 10;
        $infusion_pump = [
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'I2', 'value' => '0 / X - 21 / E - 000.00 DL'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E4', 'value' => 'Bbraun'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E5', 'value' => 'B'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E6', 'value' => 'C'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'C7', 'value' => '(0 - 500) mL/h'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'C8', 'value' => '(100 - 500) mL/h'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E7', 'value' => 0.01],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E8', 'value' => 0.10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E9', 'value' => '2021-10-14'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E10', 'value' => '2021-10-14'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E11', 'value' => 'D'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E12', 'value' => 'E'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E17', 'value' => 21],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E18', 'value' => 21.4],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'F17', 'value' => 70],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'F18', 'value' => 70.7],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E19', 'value' => 220],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E22', 'value' => 'Baik'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'E23', 'value' => 'Baik'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J27', 'value' => 10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'C28', 'value' => 'Resistansi Pembumian Protektif (kabel dapat dilepas)'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J28', 'value' => 0.100],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'C29', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J29', 'value' => 100],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'F34', 'value' => 10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'F35', 'value' => 50],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'F36', 'value' => 100.10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'F37', 'value' => 500],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'G34', 'value' => 10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'G35', 'value' => 50],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'G36', 'value' => 100.10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'G37', 'value' => 500],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'H34', 'value' => 10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'H35', 'value' => 50],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'H36', 'value' => 100.10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'H37', 'value' => 500],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'I34', 'value' => 10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'I35', 'value' => 50],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'I36', 'value' => 100.10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'I37', 'value' => 500],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J34', 'value' => 10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J35', 'value' => 50],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J36', 'value' => 100.10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J37', 'value' => 500],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'K34', 'value' => 10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'K35', 'value' => 50],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'K36', 'value' => 100.10],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'K37', 'value' => 500],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'F41', 'value' => 18],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'G41', 'value' => 18],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'H41', 'value' => 18],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'I41', 'value' => 18],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'J41', 'value' => 18],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'K41', 'value' => 18],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'B48', 'value' => 'Infusion device analyzer menggunakan channel 4 (IDA 5, SN : 5157005)'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'D49', 'value' => 'Otsuka, 20 drops'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'B56', 'value' => 'Thermohygrolight, Merek : EXTECH, Model : SD700, SN : A.100586'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'B54', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 4669058'],
            ['external_alkes_order_id' => $infusion_pump_order_id , 'cell' => 'B66', 'value' => 'Donny Martha'],
        ];

        $worksheets = [
            ...$flowmeter_worksheet,
            ...$timbangan_bayi_worksheet,
            ...$nebulizer_worksheet,
            ...$suction_pump_worksheet,
            ...$patient_monitor_worksheet,
            ...$centrifuge_worksheet,
            ...$dental_unit_worksheet,
            ...$fetal_doppler_worksheet,
            ...$ecg_recorder_worksheet,
            ...$infusion_pump
        ];

        foreach($worksheets as $worksheet){
            ExternalOrderExcelValue::create($worksheet);
        }
    }
}
