<?php

namespace Database\Seeders;

use App\Models\ExternalOrderExcelValue;
use Illuminate\Database\Seeder;

class ExternalOrderExcelValueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $flowmeter_order_id = 1;
        $flowmeter_worksheet = [
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I2', 'value' => '1 / III - 22 / E - 0.0 DL'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E5', 'value' => 'Avico'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E6', 'value' => '-'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E7', 'value' => '-'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E8', 'value' => '1'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E9', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E10', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E11', 'value' => 'Laboratorium Kalibrasi LPFK Banjarbaru'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E12', 'value' => 'IGD'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E17', 'value' => 22.4],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F17', 'value' => 22.7],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E18', 'value' => 67.4],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F18', 'value' => 67.8],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E22', 'value' => 'Baik'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I27', 'value' => 1000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I28', 'value' => 2000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I29', 'value' => 3000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I30', 'value' => 4000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I31', 'value' => 5000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I32', 'value' => 6000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'E33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'F33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'G33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'H33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'I33', 'value' => 7000],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B38', 'value' => 'Pembacaan skala dibawah bola'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B41', 'value' => 'Gas Flow Analyzer, Merek : Fluke, Model : VT900A, SN : 5101752-5102038'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B42', 'value' => 'Thermohygrolight, Merek : KIMO, Model : KH-210-AO, SN : 15062873'],
            ['external_alkes_order_id' => $flowmeter_order_id, 'cell' => 'B49', 'value' => 'Muhammad Irfan Husnuzhzhan']
        ];

        $timbangan_bayi_order_id = 2;
        $timbangan_bayi_worksheet = [
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'I2', 'value' => '3 / I - 17 / E - 001.03 DL'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D4', 'value' => '-'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D5', 'value' => '-'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D6', 'value' => '-'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D7', 'value' => 0.005],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F7', 'value' => 'Digital'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D8', 'value' => '2022-01-15'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D9', 'value' => '2022-01-15'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D10', 'value' => 'laboratorium kalibrasi lpfk banjarbaru'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D11', 'value' => 'laboratorium kalibrasi lpfk banjarbaru'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D16', 'value' => 22],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E16', 'value' => 24],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D17', 'value' => 60],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E17', 'value' => 63],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D22', 'value' => 'Baik'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C30', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D30', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F30', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G30', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C31', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D31', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F31', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G31', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C32', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D32', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F32', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G32', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C33', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D33', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F33', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G33', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C34', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D34', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F34', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G34', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C35', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D35', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F35', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G35', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C36', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D36', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F36', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G36', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C37', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D37', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F37', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G37', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C38', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D38', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F38', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G38', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C39', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D39', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F39', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G39', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C44', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D44', 'value' => 1.05],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E44', 'value' => 1.05],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F44', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C45', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D45', 'value' => 2],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E45', 'value' => 2],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F45', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C46', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D46', 'value' => 3],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E46', 'value' => 3],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F46', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C48', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D48', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E48', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F48', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C53', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D53', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E53', 'value' => 10],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F53', 'value' => 0],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G57', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'C58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'D58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'E58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'F58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'G58', 'value' => 5],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'B68', 'value' => 'Anak Timbangan Standar, Merek : HÄFNER, Model : 7.MEHM-210, SN : 1060716'],
            ['external_alkes_order_id' => $timbangan_bayi_order_id, 'cell' => 'B72', 'value' => 'Thermohygrolight, Merek : KIMO, Model : KH-210-AO, SN : 15062874'],
        ];

        $nebulizer_order_id = 3;
        $nebulizer_worksheet = [
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I2', 'value' => '1 / III - 22 / E - 0.0 DL'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E4', 'value' => 'OMRON'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E5', 'value' => 'CX 4'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E6', 'value' => '1946'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E7', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E8', 'value' => '2022-03-01'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E9', 'value' => 'Laboratorium Kalibrasi LPFK Banjarbaru'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E10', 'value' => 'P2M'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E15', 'value' => 25.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'F15', 'value' => 25.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E16', 'value' => 70.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'F16', 'value' => 70.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E17', 'value' => 228],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E20', 'value' => 'Baik'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E21', 'value' => 'Baik'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I25', 'value' => 7],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'C26', 'value' => 'Resistansi Pembumian Protektif (kabel tidak dapat dilepas)'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I26', 'value' => 0.120],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'C27', 'value' => 'Arus bocor peralatan untuk peralatan elektromedik kelas I'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'I27', 'value' => 12.1],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'C32', 'value' => 'Flow (L/min) (Compressor)'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'E32', 'value' => 4.3],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'F32', 'value' => 4.2],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'G32', 'value' => 4.3],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B42', 'value' => 'Gas Flow Analyzer, Merek : Fluke, Model : VT305, SN : BF102163'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B43', 'value' => 'Electrical Safety Analyzer, Merek : Fluke, Model : ESA 615, SN : 2853077'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B44', 'value' => 'Thermohygrolight, Merek : Greisinger, Model : GFTB 200, SN : 34904091'],
            ['external_alkes_order_id' => $nebulizer_order_id, 'cell' => 'B51', 'value' => 'Ryan Rama Chaesar R'],
        ];

        $worksheets = [
            ...$flowmeter_worksheet,
            ...$timbangan_bayi_worksheet,
            ...$nebulizer_worksheet
        ];

        foreach($worksheets as $worksheet){
            ExternalOrderExcelValue::create($worksheet);
        }
    }
}
